### ISSUE TITLE
Error: getNamespaceValue: Node no longer exists

### ISSUE THREAD

**Issue by acrozes** [fguillot/picoFeed#112] opened 2015-03-20 15:57 UTC
Sometimes I have this error ... maybe add a try catch ?

```
Warning: PicoFeed\Parser\XmlParser::getNamespaceValue(): Node no longer exists
```

**Comment by fguillot** [comment] 2015-03-20 16:59
Do you know which feed url is generating this error?

**Comment by acrozes** [comment] 2015-03-20 17:02
I am sorry no ... 3 or 4 in a list of 1000

**Comment by mkresin** [comment] 2015-03-25 21:36
> maybe add a try catch

You can not catch warnings in php. Beside that, a proper solution is to fix warnings instead of hiding them.

With which Feedreader do you use picoFeed? In case it is miniflux, do you have the content grabber enabled?

> I am sorry no ... 3 or 4 in a list of 1000

We need to know which feed causes the warning. Otherwise it is impossible to fix this.

Can you reliable reproduce the warning i.e. by exporting your subscriptions, removing all feeds from your Feedreader, import the subscriptions and updating the feeds? This way you can remove feeds from your subscriptions until you have found the faulty one.

**Comment by acrozes** [comment] 2015-05-14 13:38
I catch an example of this error:

bin/picofeed feed "http://www.tandfonline.com/action/showFeed?ui=0&mi=h7u81o&ai=1g8&jc=rcel20&type=etoc&feed=rss"
PHP Warning:  PicoFeed\Parser\XmlParser::getNamespaceValue(): Node no longer exists in vendor\fguillot\picofeed\lib\PicoFeed\Parser\XmlParser.php on line 274

Warning: PicoFeed\Parser\XmlParser::getNamespaceValue(): Node no longer exists in vendor\fguillot\picofeed\lib\PicoFeed\Parser\XmlParser.php on line 274
PHP Warning:  PicoFeed\Parser\XmlParser::getNamespaceValue(): Node no longer exists in vendor\fguillot\picofeed\lib\PicoFeed\Parser\XmlParser.php on line 274

Feed::id = http://www.tandfonline.com/action/showFeed?ui=0&mi=h7u81o&ai=1g8&jc=rcel20&type=etoc&feed=rss
Feed::title = http://www.tandfonline.com
Feed::feed_url = http://www.tandfonline.com/action/showFeed?ui=0&mi=h7u81o&ai=1g8&jc=rcel20&type=etoc&feed=rss
Feed::site_url = http://www.tandfonline.com
Feed::language =
Feed::description =
Feed::logo =
Feed::date = Thu, 14 May 15 13:32:27 +0000
Feed::isRTL() = false
Feed::items = 0 items

**Comment by mkresin** [comment] 2015-05-14 20:39
Bug analysis in a nutshell:

- warning is related to a SimpleXMLElement::children($uri) call on an empty SimpleXMLElement element in [getNamespaceValue](https://github.com/fguillot/picoFeed/blob/44f028f50ba15093668fb5be06e47dc91fc98440/lib/PicoFeed/Parser/XmlParser.php#L269)
- the rss 1.0 parser doesn't expect a namespaced channel element (dunno if namespaced channel elements are valid, but the feed validator doesn't complain)

**Comment by mkresin** [comment] 2015-07-13 11:18
@acrozes The issue is fixed in the latest picofeed development version. The is parsed correctly (items with content are returned) and the warning doesn't occur any longer.

Would you please test if it works for you as well and close the ticket afterwards!

**Closed** 2015-08-02 14:56 UTC
Labels: bug
